package com.example.foodndeliv.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "menu_items") // You can choose a table name
@Data
@NoArgsConstructor

public class MenuItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY) // Many menu items can belong to one restaurant
    @JoinColumn(name = "restaurant_id", nullable = false)
    @JsonBackReference
    private Restaurant restaurant;

    @Column(name = "product_name", nullable = false)
    private String productName;

    @Column(nullable = false)
    private Double price;

    @Column(name = "is_available", nullable = false)
    private boolean isAvailable = true; // Default to true, can be changed

    // Constructors, getters, setters will be generated by Lombok's @Data and @NoArgsConstructor / @AllArgsConstructor
    // You might add a specific constructor if needed:
    public MenuItem(Restaurant restaurant, String productName, Double price, boolean isAvailable) {
        this.restaurant = restaurant;
        this.productName = productName;
        this.price = price;
        this.isAvailable = isAvailable;
    }
}