apiVersion: v1
kind: Service
metadata:
  name: foodndeliv-service
spec:
  selector:
    app: foodndeliv # Must match the labels in your Deployment's template
  ports:
    - name: http
      protocol: TCP
      port: 8080       # Port the Service is available on *inside* the cluster
      targetPort: 8080 # Port your app container listens on
  type: NodePort     # Good for Minikube; exposes on Node's IP at a high port