# k8s/foodndeliv_load_test.yaml
config:
  target: "http://127.0.0.1:37217" # Gotten with "minikube service foodndeliv-service --url -n default"
  phases:
    - duration: 120  # Run for 120 seconds
      arrivalRate: 5 # Start with 5 new users per second
      rampTo: 10     # Ramp up to 10 new users per second
scenarios:
  - name: "User Workflow"
    flow:
      - get:
          url: "/api/restaurants" # Or other GET endpoints of your app
      - think: 1
      - post:
          url: "/api/ctrl/orders" # Or other POST endpoints
          json:
            customerId: 1 # Use valid IDs
            restaurantId: 1 # Use valid IDs
            state: "OPEN"
            orderDetails: "Artillery Test Order {{ $timestamp }}"
            orderLines:
              - productName: "Pizza Margherita" # Ensure this product is valid for the restaurant
                quantity: 1
      - think: 2