# foodndeliv/k8s/postgres-values.yaml
global:
  postgresql:
    auth:
      database: ordersdb      # Existing database name
      username: myappuser     # app username
      password: myapppassword # password for user
      postgresPassword: strongpostgresadminpassword # sets the 'postgres' superuser password

primary:
  persistence:
    enabled: true
    size: 1Gi # Adjust size as needed
