# k8s/prometheus-values.yaml
extraScrapeConfigs: |
  - job_name: 'foodndeliv'
    metrics_path: '/actuator/prometheus'
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
        action: keep
        regex: foodndeliv-service;default
      - source_labels: [__meta_kubernetes_service_port_name]
        action: keep
        regex: http
      - source_labels: [__address__]
        action: replace
        target_label: __address__
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}:8080